version: '3.4'

services:
  webui:
    image: ${DOCKER_REGISTRY-}webapi
    build:
      context: .
      dockerfile: src/WebUI/Dockerfile
    environment:
      - "UseInMemoryDatabase=false"
      - "ConnectionStrings__DefaultConnection=Server=db;Database=CleanArchitectureDb;User=sa;Password=password123;MultipleActiveResultSets=true"
      - "IdentityServer__Key__Type=Development"
      - "ASPNETCORE_Kestrel__Certificates__Default__Password=password123"
      - "ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx"
    volumes:
      - ~/.aspnet/https:/https:ro
    ports:
      - "5000:5000"
      - "5001:5001"
    depends_on:
      - db
    restart: on-failure

  db:
    image: "mcr.microsoft.com/azure-sql-edge"
    environment:
      - "MSSQL_DATABASE_COLLATE=SQL_Latin1_General_CP1_CI_AI"
      - "SA_PASSWORD=Test!123"
      - "ACCEPT_EULA=Y"
      - "MSSQL_PID=Developer"
      - "MSSQL_DATABASE=TestMatchProfiler"
    ports:
      - "1433:1433"